<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Person [
        <!ELEMENT Person (Student*)>
        <!ELEMENT Student (name,age,sex,birthday,school,department)>
        <!ELEMENT name (#PCDATA)>
        <!ATTLIST name ID1 CDATA #REQUIRED>

        <!ELEMENT age (#PCDATA)>
        <!ATTLIST age ID2 CDATA #IMPLIED>

        <!ELEMENT sex (#PCDATA)>
        <!ATTLIST sex ID3 (ふじん|だんせい) #REQUIRED>

        <!ELEMENT birthday (#PCDATA)>

        <!ELEMENT school (#PCDATA)>
        <!ATTLIST school ID5 CDATA #IMPLIED>

        <!ELEMENT department (#PCDATA)>
        ]
        >

<Person>
    <Student>
        <name ID1="ミク">初音ミク</name>
        <age>はたち</age>
        <sex ID3="ふじん">ふじん</sex>
        <birthday>2000-11-12</birthday>
        <school ID5="学校">わせだだいがく</school>
        <department>コンピューター</department>

    </Student>

    <Student>
        <name ID1="犬夜叉">いぬやしゃ</name>
        <age>にじゅういっさい</age>
        <sex ID3="ふじん">ふじん</sex>
        <birthday>2001-01-02</birthday>
        <school ID5="学校">せいかだいがく</school>
        <department>コンピューター</department>
    </Student>
</Person>